### ISSUE TITLE
PHP 8.2 dynamic static properties are not allowed

### ISSUE THREAD

**Issue by leichim** [creativesolvers/divergent-framework#13]
PHP 8.2 throws deprecation error for dynamic properties created in classed that extend the filed.

**Comment by henrik-dons** [comment]
![deprecated-notices](https://github.com/makeitworkpress/wp-custom-fields/assets/45787627/3a9c51c2-862b-4571-a8fe-cb73f7bbabbc)

See attached screenshot.

Deprecated notices show up when using WordPress 6.4.1 and PHP 8.2 and using example code:
https://github.com/makeitworkpress/wp-custom-fields/wiki#adding-custom-fields

**Comment by leichim** [comment]
These issues should now be resolved.
