### ISSUE TITLE
Syntax errors in code examples in documentation

### ISSUE THREAD

**Issue by RobertGard** [creativesolvers/divergent-framework#2]
You have syntax error on this page : https://github.com/makeitworkpress/wp-custom-fields/wiki/Adding-Options-Pages
![image](https://user-images.githubusercontent.com/27079677/86188064-2620a580-bb46-11ea-9088-5664c4b8288f.png)

Also on this page you have a syntax error : https://github.com/makeitworkpress/wp-custom-fields/wiki
![image](https://user-images.githubusercontent.com/27079677/86188212-9f1ffd00-bb46-11ea-8e1a-51cdcc4090bc.png)

**Comment by leichim** [comment]
Thanks for going over this and pointing out the errors. Shouldn't be there indeed!
