### ISSUE TITLE
"Repeatable" not working properly when nested

### ISSUE THREAD

**Issue by RobertGard** [creativesolvers/divergent-framework#3]
Greetings! I created the "repeatable" nesting as in the screenshot:
![image](https://user-images.githubusercontent.com/27079677/86413835-f222bd00-bcca-11ea-935d-dc5188826a32.png)

I expected that "repeatable" would work like this:

![image](https://user-images.githubusercontent.com/27079677/86414424-89d4db00-bccc-11ea-8c87-1c5b39c5b3f4.png)

No tak eto ne rabotayet, vzamesto etogo, i pervaya knopka "repeatable" (glavnogo bloka) i vtoraya knopka (dochernego bloka) dobavlyayut polya v odin blok, chto kazhetsya mne ochen' ne logichnym.
But this doesn’t work, instead of this, both the first “repeatable” button (of the main block) and the second button (of the child block) add fields to one block, which seems very logical to me.

![image](https://user-images.githubusercontent.com/27079677/86414643-38791b80-bccd-11ea-9e99-c2dc6cf8f936.png)

I really hope that you can help me with a solution to my problem. Thanks for your attention.

**Comment by RobertGard** [comment]
Is there any living here? Or is this repository abandoned?

**Comment by leichim** [comment]
Ever heard of the word patience? Devs need some holidays too ;).

Nevertheless, thanks for pointing out the error/feature. Now repeatable fields are not meant to be nested (yet), so I'll update the documentation on that. 

But, I'll add this feature to the development roadmap. It may take some time before it's developed.

**Comment by RobertGard** [comment]
Patience is a loose concept. Some things can be expected for years, but this is not the case. If I see that there is no feedback on the project and the project is not developing, then I just move on to another project and not only me do it.

**Comment by leichim** [comment]
That's fine! Thanks for sharing and adding suggestions to the project.

**Comment by RobertGard** [comment]
I understand that your project is not based on a fee basis and therefore you to anyone and owe nothing. I needed just a feedback...
Since I have your solution considered most appropriate of all those I saw.

**Comment by RobertGard** [comment]
Don't have time to add to the first answer

**Comment by leichim** [comment]
Thanks for the compliment. Well, I also value the feedback from people that are using this as it will help to make it better (and the only reason I built this, while there are many similar frameworks around, is that I didn't find a free framework covering all custom fields). But it's true, it is a free side project and I can't always give it attention. Take care!

**Comment by RobertGard** [comment]
Well, the last question. I understand that I am wasting your time, but it is important for me to know this. How long will this feature be added to wet field groups in the repeater? The fact is that this function is very important for my plugin (which I am developing). And if you are not going to add such a function in the near future, then I will have to write down the settings page of my plugin using someone else’s solution, which I don’t want to do at all, since I really like your solution.

**Comment by leichim** [comment]
Ah, I understand. Concerning the amount of work that is coming at me the last days, I fear that I'm not able to update it before August. However, I can always implement a suggested merge. I've to adapt some JS in src/assets/js/modules/repeatable.js.
