### ISSUE TITLE
does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

### ISSUE THREAD

**Issue by RobertGard** [creativesolvers/divergent-framework#4]
![image](https://user-images.githubusercontent.com/27079677/86606536-cd6f6380-bfb0-11ea-9b8a-a83833876fbc.png)

Tell me what to do with this problem? WordPress gives me this error: "Uncaught Error: Class 'MakeitWorkPress \ WP_Custom_Fields \ Framework' not found in ..."

**Comment by leichim** [comment]
Will add this to the dev-list. In the meantime, you can use the manual autoloader script as defined in the homepage of the wiki (loads all classes within /classes/ and /vendor/makeitworkpress/ vendor files.
